// 2024-07-05,17:25:05
// http://localhost:5420/api/txt2json

export const RAPID_RAIL_KL_STOPS = [
  {
    stop_id: "AG18",
    stop_name: "AMPANG",
    stop_lat: 3.150318,
    stop_lon: 101.760049,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT AMPANG",
  },
  {
    stop_id: "AG17",
    stop_name: "CAHAYA",
    stop_lat: 3.140575,
    stop_lon: 101.756677,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT CAHAYA",
  },
  {
    stop_id: "AG16",
    stop_name: "CEMPAKA",
    stop_lat: 3.138324,
    stop_lon: 101.752979,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT CEMPAKA",
  },
  {
    stop_id: "AG15",
    stop_name: "PANDAN INDAH",
    stop_lat: 3.134581,
    stop_lon: 101.746509,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PANDAN INDAH",
  },
  {
    stop_id: "AG14",
    stop_name: "PANDAN JAYA",
    stop_lat: 3.130141,
    stop_lon: 101.739122,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PANDAN JAYA",
  },
  {
    stop_id: "AG13",
    stop_name: "MALURI",
    stop_lat: 3.12329,
    stop_lon: 101.727283,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT MALURI",
  },
  {
    stop_id: "AG12",
    stop_name: "MIHARJA",
    stop_lat: 3.120973,
    stop_lon: 101.717922,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT MIHARJA",
  },
  {
    stop_id: "AG11",
    stop_name: "CHAN SOW LIN",
    stop_lat: 3.128105,
    stop_lon: 101.715637,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT CHAN SOW LIN",
  },
  {
    stop_id: "AG10",
    stop_name: "PUDU",
    stop_lat: 3.134879,
    stop_lon: 101.711957,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PUDU",
  },
  {
    stop_id: "AG9",
    stop_name: "HANG TUAH",
    stop_lat: 3.140012,
    stop_lon: 101.705984,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT HANG TUAH",
  },
  {
    stop_id: "AG8",
    stop_name: "PLAZA RAKYAT",
    stop_lat: 3.144049,
    stop_lon: 101.702105,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PLAZA RAKYAT",
  },
  {
    stop_id: "AG7",
    stop_name: "MASJID JAMEK",
    stop_lat: 3.14927,
    stop_lon: 101.696377,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT MASJID JAMEK",
  },
  {
    stop_id: "AG6",
    stop_name: "BANDARAYA",
    stop_lat: 3.155567,
    stop_lon: 101.694485,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT BANDARAYA",
  },
  {
    stop_id: "AG5",
    stop_name: "SULTAN ISMAIL",
    stop_lat: 3.161245,
    stop_lon: 101.694109,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SULTAN ISMAIL",
  },
  {
    stop_id: "AG4",
    stop_name: "PWTC",
    stop_lat: 3.166333,
    stop_lon: 101.693586,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PWTC",
  },
  {
    stop_id: "AG3",
    stop_name: "TITIWANGSA",
    stop_lat: 3.173497,
    stop_lon: 101.695367,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT TITIWANGSA",
  },
  {
    stop_id: "AG2",
    stop_name: "SENTUL",
    stop_lat: 3.178484,
    stop_lon: 101.695542,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SENTUL",
  },
  {
    stop_id: "AG1",
    stop_name: "SENTUL TIMUR",
    stop_lat: 3.185897,
    stop_lon: 101.695217,
    category: "LRT",
    route_id: "AG",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SENTUL TIMUR",
  },
  {
    stop_id: "KJ37",
    stop_name: "PUTRA HEIGHTS",
    stop_lat: 2.996227,
    stop_lon: 101.575462,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PUTRA HEIGHTS",
  },
  {
    stop_id: "KJ36",
    stop_name: "SUBANG ALAM",
    stop_lat: 3.009421,
    stop_lon: 101.572281,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SUBANG ALAM",
  },
  {
    stop_id: "KJ35",
    stop_name: "ALAM MEGAH",
    stop_lat: 3.023151,
    stop_lon: 101.572029,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT ALAM MEGAH",
  },
  {
    stop_id: "KJ34",
    stop_name: "USJ 21",
    stop_lat: 3.029881,
    stop_lon: 101.581711,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT USJ 21",
  },
  {
    stop_id: "KJ33",
    stop_name: "WAWASAN",
    stop_lat: 3.035062,
    stop_lon: 101.588348,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT WAWASAN",
  },
  {
    stop_id: "KJ32",
    stop_name: "TAIPAN",
    stop_lat: 3.04815,
    stop_lon: 101.590233,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT TAIPAN",
  },
  {
    stop_id: "KJ31",
    stop_name: "USJ 7",
    stop_lat: 3.054956,
    stop_lon: 101.592194,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT USJ 7",
  },
  {
    stop_id: "KJ30",
    stop_name: "SS 18",
    stop_lat: 3.067182,
    stop_lon: 101.585945,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SS 18",
  },
  {
    stop_id: "KJ29",
    stop_name: "SS 15",
    stop_lat: 3.075972,
    stop_lon: 101.585983,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SS 15",
  },
  {
    stop_id: "KJ28",
    stop_name: "SUBANG JAYA",
    stop_lat: 3.08466,
    stop_lon: 101.588127,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SUBANG JAYA",
  },
  {
    stop_id: "KJ27",
    stop_name: "CGC GLENMARIE",
    stop_lat: 3.094732,
    stop_lon: 101.590622,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT CGC GLENMARIE",
  },
  {
    stop_id: "KJ26",
    stop_name: "ARA DAMANSARA",
    stop_lat: 3.108643,
    stop_lon: 101.586372,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT ARA DAMANSARA",
  },
  {
    stop_id: "KJ25",
    stop_name: "LEMBAH SUBANG",
    stop_lat: 3.112094,
    stop_lon: 101.591034,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT LEMBAH SUBANG",
  },
  {
    stop_id: "KJ24",
    stop_name: "KELANA JAYA",
    stop_lat: 3.112497,
    stop_lon: 101.6043,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT KELANA JAYA",
  },
  {
    stop_id: "KJ23",
    stop_name: "TAMAN BAHAGIA",
    stop_lat: 3.11079,
    stop_lon: 101.612856,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT TAMAN BAHAGIA",
  },
  {
    stop_id: "KJ22",
    stop_name: "TAMAN PARAMOUNT",
    stop_lat: 3.104716,
    stop_lon: 101.623192,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT TAMAN PARAMOUNT",
  },
  {
    stop_id: "KJ21",
    stop_name: "ASIA JAYA",
    stop_lat: 3.104343,
    stop_lon: 101.637695,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT ASIA JAYA",
  },
  {
    stop_id: "KJ20",
    stop_name: "TAMAN JAYA",
    stop_lat: 3.104086,
    stop_lon: 101.645248,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT TAMAN JAYA",
  },
  {
    stop_id: "KJ19",
    stop_name: "UNIVERSITI",
    stop_lat: 3.114616,
    stop_lon: 101.661639,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT UNIVERSITI",
  },
  {
    stop_id: "KJ18",
    stop_name: "KERINCHI",
    stop_lat: 3.115506,
    stop_lon: 101.668572,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT KERINCHI",
  },
  {
    stop_id: "KJ17",
    stop_name: "ABDULLAH HUKUM",
    stop_lat: 3.118735,
    stop_lon: 101.672897,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT ABDULLAH HUKUM",
  },
  {
    stop_id: "KJ16",
    stop_name: "BANK RAKYAT BANGSAR",
    stop_lat: 3.127588,
    stop_lon: 101.679062,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT BANK RAKYAT BANGSAR",
  },
  {
    stop_id: "KJ15",
    stop_name: "KL SENTRAL",
    stop_lat: 3.13442,
    stop_lon: 101.68625,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT KL SENTRAL",
  },
  {
    stop_id: "KJ14",
    stop_name: "PASAR SENI",
    stop_lat: 3.142439,
    stop_lon: 101.69531,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PASAR SENI",
  },
  {
    stop_id: "KJ13",
    stop_name: "MASJID JAMEK",
    stop_lat: 3.149714,
    stop_lon: 101.696815,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT MASJID JAMEK",
  },
  {
    stop_id: "KJ12",
    stop_name: "DANG WANGI",
    stop_lat: 3.156942,
    stop_lon: 101.701975,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT DANG WANGI",
  },
  {
    stop_id: "KJ11",
    stop_name: "KAMPUNG BARU",
    stop_lat: 3.161386,
    stop_lon: 101.706608,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT KAMPUNG BARU",
  },
  {
    stop_id: "KJ10",
    stop_name: "KLCC",
    stop_lat: 3.158935,
    stop_lon: 101.713287,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT KLCC",
  },
  {
    stop_id: "KJ9",
    stop_name: "AMPANG PARK",
    stop_lat: 3.159894,
    stop_lon: 101.719017,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT AMPANG PARK",
  },
  {
    stop_id: "KJ8",
    stop_name: "DAMAI",
    stop_lat: 3.164406,
    stop_lon: 101.724489,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT DAMAI",
  },
  {
    stop_id: "KJ7",
    stop_name: '"DATO\' KERAMAT"',
    stop_lat: 3.16509,
    stop_lon: 101.73184,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: '"LRT DATO\' KERAMAT"',
  },
  {
    stop_id: "KJ6",
    stop_name: "JELATEK",
    stop_lat: 3.167204,
    stop_lon: 101.735344,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT JELATEK",
  },
  {
    stop_id: "KJ5",
    stop_name: "SETIAWANGSA",
    stop_lat: 3.17576,
    stop_lon: 101.73584,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SETIAWANGSA",
  },
  {
    stop_id: "KJ4",
    stop_name: "SRI RAMPAI",
    stop_lat: 3.199176,
    stop_lon: 101.73747,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SRI RAMPAI",
  },
  {
    stop_id: "KJ3",
    stop_name: "WANGSA MAJU",
    stop_lat: 3.205751,
    stop_lon: 101.731796,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT WANGSA MAJU",
  },
  {
    stop_id: "KJ2",
    stop_name: "TAMAN MELATI",
    stop_lat: 3.219558,
    stop_lon: 101.72197,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT TAMAN MELATI",
  },
  {
    stop_id: "KJ1",
    stop_name: "GOMBAK",
    stop_lat: 3.231793,
    stop_lon: 101.724427,
    category: "LRT",
    route_id: "KJ",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT GOMBAK",
  },
  {
    stop_id: "SP31",
    stop_name: "PUTRA HEIGHTS",
    stop_lat: 2.996016,
    stop_lon: 101.575521,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PUTRA HEIGHTS",
  },
  {
    stop_id: "SP29",
    stop_name: "PUCHONG PRIMA",
    stop_lat: 2.999808,
    stop_lon: 101.596692,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PUCHONG PRIMA",
  },
  {
    stop_id: "SP28",
    stop_name: "PUCHONG PERDANA",
    stop_lat: 3.007913,
    stop_lon: 101.605021,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PUCHONG PERDANA",
  },
  {
    stop_id: "SP27",
    stop_name: "BANDAR PUTERI",
    stop_lat: 3.017111,
    stop_lon: 101.612855,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT BANDAR PUTERI",
  },
  {
    stop_id: "SP26",
    stop_name: "TAMAN PERINDUSTRIAN PUCHONG",
    stop_lat: 3.022814,
    stop_lon: 101.613514,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT TAMAN PERINDUSTRIAN PUCHONG",
  },
  {
    stop_id: "SP25",
    stop_name: "PUSAT BANDAR PUCHONG",
    stop_lat: 3.033194,
    stop_lon: 101.616057,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PUSAT BANDAR PUCHONG",
  },
  {
    stop_id: "SP24",
    stop_name: "IOI PUCHONG JAYA",
    stop_lat: 3.048101,
    stop_lon: 101.62095,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT IOI PUCHONG JAYA",
  },
  {
    stop_id: "SP22",
    stop_name: "KINRARA",
    stop_lat: 3.050506,
    stop_lon: 101.644294,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT KINRARA",
  },
  {
    stop_id: "SP21",
    stop_name: "ALAM SUTERA",
    stop_lat: 3.0547,
    stop_lon: 101.656468,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT ALAM SUTERA",
  },
  {
    stop_id: "SP20",
    stop_name: "MUHIBBAH",
    stop_lat: 3.062229,
    stop_lon: 101.662552,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT MUHIBBAH",
  },
  {
    stop_id: "SP19",
    stop_name: "AWAN BESAR",
    stop_lat: 3.062131,
    stop_lon: 101.670555,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT AWAN BESAR",
  },
  {
    stop_id: "SP18",
    stop_name: "SRI PETALING",
    stop_lat: 3.061445,
    stop_lon: 101.687074,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SRI PETALING",
  },
  {
    stop_id: "SP17",
    stop_name: "BUKIT JALIL",
    stop_lat: 3.058196,
    stop_lon: 101.692125,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT BUKIT JALIL",
  },
  {
    stop_id: "SP16",
    stop_name: "SUNGAI BESI",
    stop_lat: 3.063842,
    stop_lon: 101.708062,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SUNGAI BESI",
  },
  {
    stop_id: "SP15",
    stop_name: "BANDAR TASIK SELATAN",
    stop_lat: 3.076058,
    stop_lon: 101.711107,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT BANDAR TASIK SELATAN",
  },
  {
    stop_id: "SP14",
    stop_name: "BANDAR TUN RAZAK",
    stop_lat: 3.089576,
    stop_lon: 101.712466,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT BANDAR TUN RAZAK",
  },
  {
    stop_id: "SP13",
    stop_name: "SALAK SELATAN",
    stop_lat: 3.102201,
    stop_lon: 101.706179,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SALAK SELATAN",
  },
  {
    stop_id: "SP12",
    stop_name: "CHERAS",
    stop_lat: 3.112609,
    stop_lon: 101.714178,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT CHERAS",
  },
  {
    stop_id: "SP11",
    stop_name: "CHAN SOW LIN",
    stop_lat: 3.128105,
    stop_lon: 101.715637,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT CHAN SOW LIN",
  },
  {
    stop_id: "SP10",
    stop_name: "PUDU",
    stop_lat: 3.134879,
    stop_lon: 101.711957,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PUDU",
  },
  {
    stop_id: "SP9",
    stop_name: "HANG TUAH",
    stop_lat: 3.140012,
    stop_lon: 101.705984,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT HANG TUAH",
  },
  {
    stop_id: "SP8",
    stop_name: "PLAZA RAKYAT",
    stop_lat: 3.144049,
    stop_lon: 101.702105,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PLAZA RAKYAT",
  },
  {
    stop_id: "SP7",
    stop_name: "MASJID JAMEK",
    stop_lat: 3.14927,
    stop_lon: 101.696377,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT MASJID JAMEK",
  },
  {
    stop_id: "SP6",
    stop_name: "BANDARAYA",
    stop_lat: 3.155567,
    stop_lon: 101.694485,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT BANDARAYA",
  },
  {
    stop_id: "SP5",
    stop_name: "SULTAN ISMAIL",
    stop_lat: 3.161245,
    stop_lon: 101.694109,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SULTAN ISMAIL",
  },
  {
    stop_id: "SP4",
    stop_name: "PWTC",
    stop_lat: 3.166333,
    stop_lon: 101.693586,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT PWTC",
  },
  {
    stop_id: "SP3",
    stop_name: "TITIWANGSA",
    stop_lat: 3.173497,
    stop_lon: 101.695367,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT TITIWANGSA",
  },
  {
    stop_id: "SP2",
    stop_name: "SENTUL",
    stop_lat: 3.178484,
    stop_lon: 101.695542,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SENTUL",
  },
  {
    stop_id: "SP1",
    stop_name: "SENTUL TIMUR",
    stop_lat: 3.185897,
    stop_lon: 101.695217,
    category: "LRT",
    route_id: "PH",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "LRT SENTUL TIMUR",
  },
  {
    stop_id: "KG04",
    stop_name: "KWASA DAMANSARA",
    stop_lat: 3.176146,
    stop_lon: 101.572052,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT KWASA DAMANSARA",
  },
  {
    stop_id: "KG05",
    stop_name: "KWASA SENTRAL",
    stop_lat: 3.170112,
    stop_lon: 101.564651,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT KWASA SENTRAL",
  },
  {
    stop_id: "KG06",
    stop_name: "KOTA DAMANSARA",
    stop_lat: 3.150134,
    stop_lon: 101.57869,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT KOTA DAMANSARA",
  },
  {
    stop_id: "KG07",
    stop_name: "SURIAN",
    stop_lat: 3.14948,
    stop_lon: 101.593925,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SURIAN",
  },
  {
    stop_id: "KG08",
    stop_name: "MUTIARA DAMANSARA",
    stop_lat: 3.155301,
    stop_lon: 101.609077,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT MUTIARA DAMANSARA",
  },
  {
    stop_id: "KG09",
    stop_name: "BANDAR UTAMA",
    stop_lat: 3.14671,
    stop_lon: 101.618599,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT BANDAR UTAMA",
  },
  {
    stop_id: "KG10",
    stop_name: "TAMAN TUN DR ISMAIL",
    stop_lat: 3.13613,
    stop_lon: 101.630539,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT TAMAN TUN DR ISMAIL",
  },
  {
    stop_id: "KG12",
    stop_name: "PHILEO DAMANSARA",
    stop_lat: 3.129864,
    stop_lon: 101.642471,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT PHILEO DAMANSARA",
  },
  {
    stop_id: "KG13",
    stop_name: "PUSAT BANDAR DAMANSARA",
    stop_lat: 3.143444,
    stop_lon: 101.662857,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT PUSAT BANDAR DAMANSARA",
  },
  {
    stop_id: "KG14",
    stop_name: "SEMANTAN",
    stop_lat: 3.150977,
    stop_lon: 101.665497,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SEMANTAN",
  },
  {
    stop_id: "KG15",
    stop_name: "MUZIUM NEGARA",
    stop_lat: 3.137317,
    stop_lon: 101.687336,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT MUZIUM NEGARA",
  },
  {
    stop_id: "KG16",
    stop_name: "PASAR SENI",
    stop_lat: 3.142293265,
    stop_lon: 101.6955642,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT PASAR SENI",
  },
  {
    stop_id: "KG17",
    stop_name: "MERDEKA",
    stop_lat: 3.141969,
    stop_lon: 101.70205,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT MERDEKA",
  },
  {
    stop_id: "KG18A",
    stop_name: "BUKIT BINTANG ",
    stop_lat: 3.146503,
    stop_lon: 101.710947,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT BUKIT BINTANG ",
  },
  {
    stop_id: "KG20",
    stop_name: "TUN RAZAK EXCHANGE",
    stop_lat: 3.142403,
    stop_lon: 101.720156,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT TUN RAZAK EXCHANGE",
  },
  {
    stop_id: "KG21",
    stop_name: "COCHRANE",
    stop_lat: 3.132829,
    stop_lon: 101.722962,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT COCHRANE",
  },
  {
    stop_id: "KG22",
    stop_name: "MALURI",
    stop_lat: 3.123623,
    stop_lon: 101.727809,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT MALURI",
  },
  {
    stop_id: "KG23",
    stop_name: "TAMAN PERTAMA",
    stop_lat: 3.112547,
    stop_lon: 101.729371,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT TAMAN PERTAMA",
  },
  {
    stop_id: "KG24",
    stop_name: "TAMAN MIDAH",
    stop_lat: 3.104505,
    stop_lon: 101.732186,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT TAMAN MIDAH",
  },
  {
    stop_id: "KG25",
    stop_name: "TAMAN MUTIARA",
    stop_lat: 3.090989,
    stop_lon: 101.740453,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT TAMAN MUTIARA",
  },
  {
    stop_id: "KG26",
    stop_name: "TAMAN CONNAUGHT",
    stop_lat: 3.079172,
    stop_lon: 101.74522,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT TAMAN CONNAUGHT",
  },
  {
    stop_id: "KG27",
    stop_name: "TAMAN SUNTEX",
    stop_lat: 3.071578,
    stop_lon: 101.763552,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT TAMAN SUNTEX",
  },
  {
    stop_id: "KG28",
    stop_name: "SRI RAYA",
    stop_lat: 3.062273,
    stop_lon: 101.772899,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SRI RAYA",
  },
  {
    stop_id: "KG29",
    stop_name: "BANDAR TUN HUSSIEN ONN",
    stop_lat: 3.048223,
    stop_lon: 101.775109,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT BANDAR TUN HUSSIEN ONN",
  },
  {
    stop_id: "KG30",
    stop_name: "BATU 11 CHERAS",
    stop_lat: 3.041339,
    stop_lon: 101.773383,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT BATU 11 CHERAS",
  },
  {
    stop_id: "KG31",
    stop_name: "BUKIT DUKUNG",
    stop_lat: 3.026413,
    stop_lon: 101.771072,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT BUKIT DUKUNG",
  },
  {
    stop_id: "KG33",
    stop_name: "SUNGAI JERNIH",
    stop_lat: 3.000948,
    stop_lon: 101.783857,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SUNGAI JERNIH",
  },
  {
    stop_id: "KG34",
    stop_name: "STADIUM KAJANG",
    stop_lat: 2.994514,
    stop_lon: 101.786338,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT STADIUM KAJANG",
  },
  {
    stop_id: "KG35",
    stop_name: "KAJANG",
    stop_lat: 2.982778,
    stop_lon: 101.790278,
    category: "MRT",
    route_id: "MRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT KAJANG",
  },
  {
    stop_id: "PY01",
    stop_name: "KWASA DAMANSARA",
    stop_lat: 3.1763324,
    stop_lon: 101.5721456,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT KWASA DAMANSARA",
  },
  {
    stop_id: "PY03",
    stop_name: "KAMPUNG SELAMAT",
    stop_lat: 3.197266,
    stop_lon: 101.578499,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT KAMPUNG SELAMAT",
  },
  {
    stop_id: "PY04",
    stop_name: "SUNGAI BULOH",
    stop_lat: 3.206429,
    stop_lon: 101.581779,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SUNGAI BULOH",
  },
  {
    stop_id: "PY05",
    stop_name: "DAMANSARA DAMAI",
    stop_lat: 3.199892,
    stop_lon: 101.592623,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT DAMANSARA DAMAI",
  },
  {
    stop_id: "PY06",
    stop_name: "SRI DAMANSARA BARAT",
    stop_lat: 3.198197,
    stop_lon: 101.608302,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SRI DAMANSARA BARAT",
  },
  {
    stop_id: "PY07",
    stop_name: "SRI DAMANSARA SENTRAL",
    stop_lat: 3.198815,
    stop_lon: 101.621396,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SRI DAMANSARA SENTRAL",
  },
  {
    stop_id: "PY08",
    stop_name: "SRI DAMANSARA TIMUR",
    stop_lat: 3.207832,
    stop_lon: 101.628716,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SRI DAMANSARA TIMUR",
  },
  {
    stop_id: "PY09",
    stop_name: "METRO PRIMA",
    stop_lat: 3.214438,
    stop_lon: 101.639402,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT METRO PRIMA",
  },
  {
    stop_id: "PY10",
    stop_name: "KEPONG BARU",
    stop_lat: 3.211663,
    stop_lon: 101.648193,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT KEPONG BARU",
  },
  {
    stop_id: "PY11",
    stop_name: "JINJANG",
    stop_lat: 3.209544,
    stop_lon: 101.655829,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT JINJANG",
  },
  {
    stop_id: "PY12",
    stop_name: "SRI DELIMA",
    stop_lat: 3.207108,
    stop_lon: 101.665749,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SRI DELIMA",
  },
  {
    stop_id: "PY13",
    stop_name: "KAMPUNG BATU",
    stop_lat: 3.205521,
    stop_lon: 101.675473,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT KAMPUNG BATU",
  },
  {
    stop_id: "PY14",
    stop_name: "KENTOMEN",
    stop_lat: 3.19563,
    stop_lon: 101.6797,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT KENTOMEN",
  },
  {
    stop_id: "PY15",
    stop_name: "JALAN IPOH",
    stop_lat: 3.189319,
    stop_lon: 101.681145,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT JALAN IPOH",
  },
  {
    stop_id: "PY16",
    stop_name: "SENTUL BARAT",
    stop_lat: 3.179369,
    stop_lon: 101.684742,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SENTUL BARAT",
  },
  {
    stop_id: "PY17",
    stop_name: "TITIWANGSA",
    stop_lat: 3.17408,
    stop_lon: 101.69581,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT TITIWANGSA",
  },
  {
    stop_id: "PY18",
    stop_name: "HOSPITAL KUALA LUMPUR",
    stop_lat: 3.17405,
    stop_lon: 101.70239,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT HOSPITAL KUALA LUMPUR",
  },
  {
    stop_id: "PY19",
    stop_name: "RAJA UDA",
    stop_lat: 3.16794,
    stop_lon: 101.71017,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT RAJA UDA",
  },
  {
    stop_id: "PY20",
    stop_name: "AMPANG PARK",
    stop_lat: 3.16225,
    stop_lon: 101.71781,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT AMPANG PARK",
  },
  {
    stop_id: "PY21",
    stop_name: "PERSIARAN KLCC",
    stop_lat: 3.15712,
    stop_lon: 101.71834,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT PERSIARAN KLCC",
  },
  {
    stop_id: "PY22",
    stop_name: "CONLAY",
    stop_lat: 3.15145,
    stop_lon: 101.71801,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT CONLAY",
  },
  {
    stop_id: "PY23",
    stop_name: "TUN RAZAK EXCHANGE",
    stop_lat: 3.14289,
    stop_lon: 101.72034,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT TUN RAZAK EXCHANGE",
  },
  {
    stop_id: "PY24",
    stop_name: "CHAN SOW LIN",
    stop_lat: 3.12839,
    stop_lon: 101.71663,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT CHAN SOW LIN",
  },
  {
    stop_id: "PY27",
    stop_name: "KUCHAI",
    stop_lat: 3.089546,
    stop_lon: 101.694124,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT KUCHAI",
  },
  {
    stop_id: "PY28",
    stop_name: "TAMAN NAGA EMAS",
    stop_lat: 3.077688,
    stop_lon: 101.699867,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT TAMAN NAGA EMAS",
  },
  {
    stop_id: "PY29",
    stop_name: "SUNGAI BESI",
    stop_lat: 3.063737,
    stop_lon: 101.7084,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SUNGAI BESI",
  },
  {
    stop_id: "PY31",
    stop_name: "SERDANG RAYA UTARA",
    stop_lat: 3.041674,
    stop_lon: 101.704928,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SERDANG RAYA UTARA",
  },
  {
    stop_id: "PY32",
    stop_name: "SERDANG RAYA SELATAN",
    stop_lat: 3.028463,
    stop_lon: 101.707514,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SERDANG RAYA SELATAN",
  },
  {
    stop_id: "PY33",
    stop_name: "SERDANG JAYA",
    stop_lat: 3.0216,
    stop_lon: 101.709,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT SERDANG JAYA",
  },
  {
    stop_id: "PY34",
    stop_name: "UPM",
    stop_lat: 3.008489,
    stop_lon: 101.705396,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT UPM",
  },
  {
    stop_id: "PY36",
    stop_name: "TAMAN EQUINE",
    stop_lat: 2.98942,
    stop_lon: 101.67244,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT TAMAN EQUINE",
  },
  {
    stop_id: "PY37",
    stop_name: "PUTRA PERMAI",
    stop_lat: 2.98339,
    stop_lon: 101.66099,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT PUTRA PERMAI",
  },
  {
    stop_id: "PY38",
    stop_name: "16 SIERRA",
    stop_lat: 2.964974,
    stop_lon: 101.654812,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT 16 SIERRA",
  },
  {
    stop_id: "PY39",
    stop_name: "CYBERJAYA UTARA",
    stop_lat: 2.95,
    stop_lon: 101.6573,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT CYBERJAYA UTARA",
  },
  {
    stop_id: "PY40",
    stop_name: "CYBERJAYA CITY CENTRE",
    stop_lat: 2.9384,
    stop_lon: 101.6659,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT CYBERJAYA CITY CENTRE",
  },
  {
    stop_id: "PY41",
    stop_name: "PUTRAJAYA SENTRAL",
    stop_lat: 2.9313,
    stop_lon: 101.6715,
    category: "MRT",
    route_id: "PYL",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MRT PUTRAJAYA SENTRAL",
  },
  {
    stop_id: "MR1",
    stop_name: "KL SENTRAL",
    stop_lat: 3.132852,
    stop_lon: 101.687817,
    category: "MR",
    route_id: "MR",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MR KL SENTRAL",
  },
  {
    stop_id: "MR2",
    stop_name: "TUN SAMBANTHAN",
    stop_lat: 3.13132,
    stop_lon: 101.69085,
    category: "MR",
    route_id: "MR",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MR TUN SAMBANTHAN",
  },
  {
    stop_id: "MR3",
    stop_name: "MAHARAJALELA",
    stop_lat: 3.138743,
    stop_lon: 101.699268,
    category: "MR",
    route_id: "MR",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MR MAHARAJALELA",
  },
  {
    stop_id: "MR4",
    stop_name: "HANG TUAH",
    stop_lat: 3.140511,
    stop_lon: 101.706029,
    category: "MR",
    route_id: "MR",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MR HANG TUAH",
  },
  {
    stop_id: "MR5",
    stop_name: "IMBI",
    stop_lat: 3.14283,
    stop_lon: 101.70945,
    category: "MR",
    route_id: "MR",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MR IMBI",
  },
  {
    stop_id: "MR6",
    stop_name: "BUKIT BINTANG ",
    stop_lat: 3.146022,
    stop_lon: 101.7115,
    category: "MR",
    route_id: "MR",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MR BUKIT BINTANG ",
  },
  {
    stop_id: "MR7",
    stop_name: "RAJA CHULAN",
    stop_lat: 3.150878,
    stop_lon: 101.710432,
    category: "MR",
    route_id: "MR",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MR RAJA CHULAN",
  },
  {
    stop_id: "MR8",
    stop_name: "BUKIT NANAS",
    stop_lat: 3.156214,
    stop_lon: 101.704809,
    category: "MR",
    route_id: "MR",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MR BUKIT NANAS",
  },
  {
    stop_id: "MR9",
    stop_name: "MEDAN TUANKU",
    stop_lat: 3.15935,
    stop_lon: 101.69888,
    category: "MR",
    route_id: "MR",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MR MEDAN TUANKU",
  },
  {
    stop_id: "MR10",
    stop_name: "CHOW KIT",
    stop_lat: 3.167358,
    stop_lon: 101.698379,
    category: "MR",
    route_id: "MR",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MR CHOW KIT",
  },
  {
    stop_id: "MR11",
    stop_name: "TITIWANGSA",
    stop_lat: 3.173192,
    stop_lon: 101.696022,
    category: "MR",
    route_id: "MR",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "MR TITIWANGSA",
  },
  {
    stop_id: "BRT1",
    stop_name: "SUNWAY-SETIA JAYA",
    stop_lat: 3.0828,
    stop_lon: 101.6123,
    category: "BRT",
    route_id: "BRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "BRT SUNWAY-SETIA JAYA",
  },
  {
    stop_id: "BRT2",
    stop_name: "MENTARI",
    stop_lat: 3.0761,
    stop_lon: 101.6101,
    category: "BRT",
    route_id: "BRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "BRT MENTARI",
  },
  {
    stop_id: "BRT3",
    stop_name: "SUNWAY LAGOON ",
    stop_lat: 3.0706,
    stop_lon: 101.6107,
    category: "BRT",
    route_id: "BRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "BRT SUNWAY LAGOON ",
  },
  {
    stop_id: "BRT4",
    stop_name: "SUNMED",
    stop_lat: 3.0656,
    stop_lon: 101.6087,
    category: "BRT",
    route_id: "BRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "BRT SUNMED",
  },
  {
    stop_id: "BRT5",
    stop_name: "SunU-Monash",
    stop_lat: 3.0654,
    stop_lon: 101.6016,
    category: "BRT",
    route_id: "BRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "BRT SunU-Monash",
  },
  {
    stop_id: "BRT6",
    stop_name: "SOUTH QUAY-USJ 1",
    stop_lat: 3.0617,
    stop_lon: 101.5969,
    category: "BRT",
    route_id: "BRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "BRT SOUTH QUAY-USJ 1",
  },
  {
    stop_id: "BRT7",
    stop_name: "USJ7",
    stop_lat: 3.0553,
    stop_lon: 101.5919,
    category: "BRT",
    route_id: "BRT",
    geometry: "[object Object]",
    isOKU: true,
    status: "valid",
    search: "BRT USJ7",
  },
];
